<?php
// action_ids.php

define('ACTION_CREATE_COORDINATOR', 1);
define('ACTION_UPDATE_COORDINATOR', 2);
define('ACTION_DELETE_COORDINATOR', 3);
define('ACTION_CREATE_PROGRAM', 4);
define('ACTION_UPDATE_PROGRAM', 5);
define('ACTION_DELETE_PROGRAM', 6);
define('ACTION_CREATE_COMPANY', 7);
define('ACTION_UPDATE_COMPANY', 8);
define('ACTION_DELETE_COMPANY', 9);
define('ACTION_DELETE_STUDENT', 10);
define('ACTION_LOGIN', 11);
define('ACTION_LOGOUT', 12);
define('ACTION_EXPORT_DATA', 13);
define('ACTION_IMPORT_DATA', 14);
define('ACTION_CHANGE_SETTINGS', 15);
define('ACTION_SECURITY_AUDIT', 16);
?>
